language: node_js
install:
- curl -s https://www.parse.com/downloads/cloud_code/installer.sh | sudo /bin/bash
before_script:
- /bin/echo "${ACCOUNT_KEY}" | /usr/local/bin/parse configure accountkey -d
script:
- /usr/local/bin/parse deploy -f
env:
  global:
   secure: "cX+HqE9a0kVZnxzA1POEkLcdbrh2rQBrNQbnzbXUUa1A2M450R1bWyi9CzXEZH0R0dHioP+2CsjjbxaA3K4I0gD22iX7y1LCD1YUNSCs0z+tSYHO9iEtfdoAJPxJ0LejMAQ/CKI6kXH4KEfe8NBg08NxBZj5/IJVOyc9SZFcrKjuOjLKnZ6I59an5r/+pLhBs7ZA/Hc/KWu4X7Zz2gMZGM/NCVRCFEY+IdivdnOZ0pp+HqYXFPgHGE3oGyv2wzlLuWnLS2X4L0tA8oWYF6RN2odgxCxmz5RnjWhhqW6fYxLnqra7fG7zPORUdT+zmew2JhSKDXRwhCHBiDgeQL4Yc0X6+ymkEa9Ys9zdlOb0TfrlGlgSaLJYznvOZpKETdhVxv+rWT5sfDl/G0w/5mW+P+NyGos+hwfA6LlEYnuqw/pb1PxcatUHC+XFu/6/m2dE4ioK+INWB4GWfhDSFKY4YmWYf+IzRrrpXws4EQ0pMbmFmspy6s47UfG3Mzqr2Vn9+7bce2Y6oAtplUNyPW589tobPcxP8gCbaZX1Uzgag6cbbpdLA8kL7oxswkUqi+DCjOF2g3wixfHKXeE4vQcPHDGZn9F2xl5QbG4Gm0QPQAHDqSwuAcHflHqkKEbmreuyoW1+4LT7uOhDTdRFDSLE40ayv2wtBkiyZD16FdW3rvE="
notifications:
  email: false


